; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.
#include "CodeDependencies.iss"

#define MyAppName "BlueM.Wave"
#define MyAppExeName "Wave.exe"
#define MyAppPublisher "BlueM Dev Group"
#define MyAppURL "https://github.com/bluemodel/BlueM.Wave"
#ifndef MySourceDir
  // if source dir is not defined as commandline parameter using /DMySourceDir=<path>, fall back to path used by Visual Studio build
  #define MySourceDir "..\source\bin\x64\Release\net10.0-windows"
#endif
#ifndef MyAppVersion
  // if version is not passed as commandline parameter using /DMyAppVersion=<X.X.X>, fall back to version stored in executable
  #define MyAppVersionFull GetVersionNumbersString(MySourceDir+"\"+MyAppExeName)
  #define MyAppVersion Copy(MyAppVersionFull, 0, RPos(".", MyAppVersionFull) - 1)
#endif
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{536A3216-C6D1-4EEA-8C33-244B845C328B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer (requires Inno Setup 7).
;SetupArchitecture=x64
ChangesAssociations=yes
DisableProgramGroupPage=yes
LicenseFile=..\COPYING.LESSER
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
CloseApplications=yes
OutputDir=.\
OutputBaseFilename=BlueM.Wave_{#MyAppVersion}_x64_setup 
SetupIconFile=.\assets\wave.ico
SolidCompression=yes
WizardStyle=modern dynamic
; Set wizard images
WizardImageFile=.\assets\WizardImageFile.png
WizardImageFileDynamicDark=.\assets\WizardImageFile.png
WizardSmallImageFile=.\assets\WizardSmallImageFile.png
WizardSmallImageFileDynamicDark=.\assets\WizardSmallImageFile.png

[Code]
function InitializeSetup: Boolean;
begin
  // add dependencies
  Dependency_AddDotNet100Desktop; // .NET 10 Desktop Runtime

  Result := True;
end;

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#MySourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: ".\assets\wvp.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: ".\assets\ten.ico"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Registry]
; Associate wvp files
Root: HKA; Subkey: "Software\Classes\.wvp\OpenWithProgids"; ValueType: string; ValueName: "WaveProjectFile.wvp"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\WaveProjectFile.wvp"; ValueType: string; ValueName: ""; ValueData: "Wave project file"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\WaveProjectFile.wvp\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\wvp.ico"
Root: HKA; Subkey: "Software\Classes\WaveProjectFile.wvp\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".wvp"; ValueData: "" 

; Associate ten files
Root: HKA; Subkey: "Software\Classes\.ten\OpenWithProgids"; ValueType: string; ValueName: "WaveChart.ten"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\WaveChart.ten"; ValueType: string; ValueName: ""; ValueData: "Wave chart"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\WaveChart.ten\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\ten.ico"
Root: HKA; Subkey: "Software\Classes\WaveChart.ten\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".ten"; ValueData: "" 

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

