name: DocFX Build and Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-docs:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Create TeeChart license file from secret
        uses: lukasa1993/secret-file-action@v1.0.4
        id: teechart-license
        with:
          secret: ${{ secrets.TEECHARTLICENSE }}
          b64-decode: false
      - name: Copy TeeChart license file
        run: copy ${{ steps.teechart-license.outputs.file }} "source\My Project\TeeChart.licenses"
      - name: Build Wave
        run: msbuild source\Wave.vbproj -restore -property:Platform=x64 -property:Configuration=Release
      - name: Install DocFX
        run: dotnet tool install -g docfx
      - name: Build documentation using docfx
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false
      - name: Publish
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site
          force_orphan: true        
