name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Add vstest to PATH
        uses: darenm/Setup-VSTest@v1
      - name: Create empty TeeChart license file
        run: copy /Y nul > "source\My Project\TeeChart.licenses"
        shell: cmd
      - name: Build Wave
        run: msbuild source\Wave.vbproj -restore -property:Platform=x64 -property:Configuration=Debug
      - name: Build Wave.Tests
        run: msbuild tests\Wave.Tests.vbproj -restore -property:Platform=x64 -property:Configuration=Debug
      - name: Run Tests
        run: vstest.console.exe tests\bin\x64\Debug\Wave.Tests.dll /Platform:x64